rates:
  - ["k1", 0.05]
  - ["k2", 0.5]
  - ["k3", 2]
  - {"vary": True,"non-negative": True}

inputs:
  - ["1", 0.5, {"vary": False}]
  - ["2", 0.051]
  - ["3", 0.252]
  - ["7", 0.0521]
  - ["8", 0.22]
  - ["9", 0.0522]
  - ["10", 0.22]
  - {"non-negative": True}

irf:
  - ["center1",0.4]
  - ["center2",0.4]
  - ["center3",0.4]
  - ["width", 0.06]
  - ['dispc',500, {vary: False}]
  - ['disp1',0.01]
  - ['disp2',0.001]


scale:
  - ["1", 1, {"vary": False}]
  - ["2", 1.3, {"vary": True}]
  - ["3", 1.1, {"vary": True}]

pen:
  - ["1", 1, {"vary": False}]

area:
  - ["1", 1, {"vary": False}]

