rates:
  - ["k1", 0.04996312]
  - ["k2", 1.9917]
  - ["k3", 0.499010]
  - {"vary": True,"non-negative": True}

inputs:
  - ["1", 0.5, {"vary": False}]
  - ["2", 0.24229]
  - ["3", 0.36318]
  - ["7", 0.16137]
  - ["8", 0.31157]
  - ["9", 0.09617]
  - ["10", 0.20806]
  - {"non-negative": True}

irf:
  - ["center1",0.499983]
  - ["center2",0.400024]
  - ["center3",0.3000911]
  - ["width1",0.059963]
  - ["width2",0.0899015]
  - {"non-negative": True}

scale:
  - ["1", 1, {"vary": False}]
  - ["2", 0.8800517, {"vary": True}]
  - ["3", 72.73, {"vary": True}]
  - {"non-negative": True}

area:
  - ["1", 1, {"vary": False}]

