rates:
  - ["k1", 0.05]
  - ["k2", 0.5]
  - ["k3", 2]
  - {"vary": True,"non-negative": True}

inputs:
  - ["1", 0.5, {"vary": False}]
  - ["2", 0.251]
  - ["3", 0.252]
  - ["7", 0.21]
  - ["8", 0.22]
  - ["9", 0.22]
  - ["10", 0.22]
  - {"non-negative": True}

irf:
  - ["center1",0.5]
  - ["center2",0.5]
  - ["center3",0.5]
  - ["width1",0.06]
  - ["width2",0.06]

scale:
  - ["1", 1, {"vary": False}]
  - ["2", 1.3, {"vary": True}]
  - ["3", 77, {"vary": True}]

pen:
  - ["1", 1, {"vary": False}]

area:
  - ["1", 1, {"vary": False}]

